### ISSUE TITLE
Windows 10 x64 and RTL SDR

### ISSUE THREAD

**Issue by MrKalach** [ChristopheJacquet/RdsSurveyor#26]
So, the problem is that RdsSurvey cannot load rtl sdr libs, and I'm always getting the error: 
> D:\downloads\rdssurveyor>java -jar rdssurveyor.jar 
> RDS Surveyor - (C) Christophe Jacquet and contributors, 2009-2018.
> libusb-1.0.dll: cannot load library
> libusb-1.0.dll: cannot load library
> rtl.dll: cannot load library
> rtl.dll: cannot load library
> rtl.dylib: cannot load library
> rtl.dylib: cannot load library
> rtlsdr.dll: cannot load library
> rtlsdr.dll: cannot load library
> A source or a set of TMC location tables must be provided. Aborting.

and from java part:
>         at eu.jacquet80.rds.ui.InputSelectionDialog.guessTuner(InputSelectionDialog.java:113)
>         at eu.jacquet80.rds.ui.InputSelectionDialog.actionPerformed(InputSelectionDialog.java:133)
>         at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
>         at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
>         at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
>         at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
>         at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
>         at java.awt.Component.processMouseEvent(Unknown Source)
>         at javax.swing.JComponent.processMouseEvent(Unknown Source)
>         at java.awt.Component.processEvent(Unknown Source)
>         at java.awt.Container.processEvent(Unknown Source)
>         at java.awt.Component.dispatchEventImpl(Unknown Source)
>         at java.awt.Container.dispatchEventImpl(Unknown Source)
>         at java.awt.Component.dispatchEvent(Unknown Source)
>         at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
>         at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
>         at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
>         at java.awt.Container.dispatchEventImpl(Unknown Source)
>         at java.awt.Window.dispatchEventImpl(Unknown Source)
>         at java.awt.Component.dispatchEvent(Unknown Source)
>         at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>         at java.awt.EventQueue.access$500(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue.dispatchEvent(Unknown Source)
>         at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.run(Unknown Source)

ps. Hardwrae working fine, checked by SDRSharp.

**Comment by ChristopheJacquet** [comment]
Yes, the provided Windows drivers are 32-bit libraries. They do not work with 64-bit Java Virtual Machines. You can compile them on your system. I currently don't have a setup to generate 64-bit Windows libraries, but I'm looking into cross-compiling options. Stay tuned!

**Comment by ChristopheJacquet** [comment]
May you try again with the latest release at http://rds-surveyor.jacquet.xyz/download/ ? It now has a 64-bit driver for the RTL-SDR. It should work, but I can't test myself.

**Comment by MrKalach** [comment]
Works! Thank you! 👍 The issue can be closed.
