### ISSUE TITLE
where do i get the dllinfo.o file?

### ISSUE THREAD

**Issue by Juras666** [ChristopheJacquet/RdsSurveyor#36]
Hello,
i have a problem with the Makefile.windows. The dllinfo.o file is not in the JNIBackends/rtl2832 folder.
does anyone know how to get that file?
maybe i missread something but i don't need the librtlsdr-dev for windows, or do i? 
im new to programming and would be thankful for any advice. :)

kind regards

**Comment by ChristopheJacquet** [comment]
dllinfo.o is generated from dllinfo.rc.

You could run `make dllinfo` to build it (see https://github.com/ChristopheJacquet/RdsSurveyor/blob/master/JNIBackends/Si470x/Makefile.windows#L11). However just running `make all` should also work.

Please reopen the issue if needed.
