### ISSUE TITLE
GnsGroupReader.java:595: RSSI values > 0x0F observed.

### ISSUE THREAD

**Issue by JacekRuzyczka** [ChristopheJacquet/RdsSurveyor#37]
I've found out that as a response to opcode 0x6C (OPCODE_RSSI), 0x1A and 0x1F may be returned, so that 0x0F is not the upper limit you assumed.

Tested with a GNS FM9 dongle.

**Comment by mvglasow** [comment]
Thanks, good catch! That explains why the signal strength with the GNS FM9 looked so much better than with the other receivers… If you ever get a return value above 0x1f, please let me know!

**Comment by JacekRuzyczka** [comment]
The highest RSSI value I've been able to observe so far has been 0x2C.

**Comment by mvglasow** [comment]
That means the upper limit is probably at least 0x3F, I’ve created #43 to implement that
